### ISSUE TITLE
SSP- When saving and quitting, the game crashes.

### ISSUE THREAD

**Issue by Yamza** [Maciej916/Ma-Chat#2]
**Describe the bug**
SSP-  When saving and quitting, the game crashes.

**To Reproduce**
1. Save and Quit
2. Crash

**Expected behavior**
Return to main menu.

**Versions**
- **Ma Chat**: Ma-Chat-1.15.1-1.4.0.jar Ma Chat
- **Forge**: 30.0.30

**Additional context**
https://pastebin.com/zsMSkYFA

**Comment by Maciej916** [comment]
Fixed in v1.4.1
